### ISSUE TITLE
it would be interesting to have a way to view all the potential duplicates for an item and then flag which gets kept and which are deleted

### ISSUE THREAD

**Issue by theTrumpDump** [the-trump-dump/editor-view#6]

**Comment by joshlong** [comment]
This would require backend endpoints. I’m envisioning that the client would get the next ID, load that record into the UI, then find similar records.

**Comment by theTrumpDump** [comment]
this is effectively fixed now. you can see all the bookmarks with issues and then fix them. it doesn't show you duplicates as - most of the time - bookmarks with similar descriptions are not duplicates, but instead are from the same website.
